# Generated by Django 3.1.5 on 2021-02-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_auto_20210212_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.client')),
            ],
        ),
    ]
